package exception.runtimeexception.test;

public class RuntimeExceptionTest {

	public static void main(String[] args) {
		
		//Exceptions Uncheckeds (nao checadas, pq ja existe excecao criada para elas)!!
		
		//AritmethicException (divisao por zero):
		//modo de resolver:
		int a = 10;
		int b = 0;
		if(b != 0) {
			int c = a/b;
			System.out.println(c);
		}
		
		//NullPointerException:
		Object o = null; //objeto nao inicializado tentando acessar um metodo!!
		//System.out.println(o.toString());
		
		//ArrayIndexOutOfBoundException:
		int [] ar = new int[2]; 
		System.out.println(ar[2]); //indice impresso esta fora do array!!
	}
}
